AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - Nested stacks - Root template (uksb-1q9p31idr) (tag:nested-stacks).

Parameters:
  S3BucketName:
    Description: S3 bucket name for the Nested Stacks. S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Type: String
    AllowedPattern: ^(?!(^xn--|.+-s3alias$))^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$
    ConstraintDescription: Bucket name can include numbers, lowercase letters, uppercase letters, periods (.), and hyphens (-). It cannot start or end with a hyphen (-).

  AvailabilityZones:
    Description: The list of Availability Zones to use for the subnets in the VPC.
    Type: List<AWS::EC2::AvailabilityZone::Name>

  VPCName:
    Description: The name of the VPC.
    Type: String
    Default: cfn-workshop-vpc

  VPCCidr:
    Description: The CIDR block for the VPC.
    Type: String
    Default: 10.72.0.0/16
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28

  PublicSubnetName:
    Type: String
    Description: The name of the public subnet.

  PublicSubnetCidr:
    Description: The CIDR block for the public subnet located in Availability Zone 1.
    Type: String
    Default: 10.72.32.0/24
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28

  PrivateSubnet1Name:
    Type: String
    Description: The name of the private subnet 1.

  PrivateSubnet1Cidr:
    Description: The CIDR block for the public subnet located in Availability Zone 2.
    Type: String
    Default: 10.72.0.0/24
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28

  PrivateSubnet2Name:
    Type: String
    Description: The name of the private subnet 2.

  PrivateSubnet2Cidr:
    Description: The CIDR block for the public subnet located in Availability Zone 2.
    Type: String
    Default: 10.72.1.0/24
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28

  # For RDS
  DBInstanceID:
    Default: wodwhora
    Description: DB Instance ID
    Type: String
    MinLength: "1"
    MaxLength: "63"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.
  DBName:
    Default: WODWHORA
    Description: DB Instance Name
    Type: String
    MinLength: "1"
    MaxLength: "64"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  DBInstanceClass:
    Default: db.t2.micro
    Description: DB instance class
    Type: String
    ConstraintDescription: Must select a valid DB instance type.
    AllowedValues:
      - db.t2.micro
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
  DBAllocatedStorage:
    Default: "20"
    Description: The size of the database (GiB)
    Type: Number
    MinValue: "20"
    MaxValue: "65536"
    ConstraintDescription: must be between 20 and 65536 GiB.
  DBUsername:
    NoEcho: "true"
    Description: Username for MySQL database access
    Type: String
    MinLength: "1"
    MaxLength: "16"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: "true"
    Description: Password MySQL database access
    Type: String
    MinLength: "8"
    MaxLength: "41"
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must contain only alphanumeric characters.
  StorageType:
    Default: gp3
    Description: Storage Type
    Type: String
  Timezone:
    Default: Asia/Tokyo
    Description: Timezone
    Type: String
  Environment:
    Description: Environment
    Type: String
    AllowedValues:
      - dev
      - test
      - prod

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/vpc.yaml
      TimeoutInMinutes: 20
      Parameters:
        AvailabilityZones: !Ref AvailabilityZones
        VPCName: !Ref VPCName
        VPCCidr: !Ref VPCCidr
        PublicSubnetName: !Ref PublicSubnetName
        PublicSubnetCidr: !Ref PublicSubnetCidr
        PrivateSubnet1Name: !Ref PrivateSubnet1Name
        PrivateSubnet1Cidr: !Ref PrivateSubnet1Cidr
        PrivateSubnet2Name: !Ref PrivateSubnet2Name
        PrivateSubnet2Cidr: !Ref PrivateSubnet2Cidr

  RdsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/rds.yaml
      TimeoutInMinutes: 20
      Parameters:
        DBInstanceID: !Ref DBInstanceID
        DBName: !Ref DBName
        DBInstanceClass: !Ref DBInstanceClass
        AvailabilityZone: !Select [0, !Ref AvailabilityZones]
        DBAllocatedStorage: !Ref DBAllocatedStorage
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        StorageType: !Ref StorageType
        Timezone: !Ref Timezone
        DBSubnetGroupName: !Sub "${VPCName}-dwh-${Environment}-int"
        DBParameterGroupName: !Sub "${DBInstanceID}-${Environment}-int"
        DBOptionGroupName: !Sub "${DBInstanceID}-${Environment}-int"

  # IamStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/iam.yaml
  #     TimeoutInMinutes: 10

  # EC2Stack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/ec2.yaml
  #     TimeoutInMinutes: 20
  #     Parameters:
  #       EnvironmentType: !Ref EnvironmentType
  #       VpcId: !GetAtt VpcStack.Outputs.VpcId
  #       SubnetId: !GetAtt VpcStack.Outputs.PublicSubnet1
  #       WebServerInstanceProfile: !GetAtt IamStack.Outputs.WebServerInstanceProfile
